name: auto-release

on:
  workflow_run:
    workflows: ["release-prepare"]
    types:
      - completed

env:
  NUGET_API_TOKEN: ${{ secrets.LLAMA_SHARP_NUGET_KEY }}

jobs:
  release_to_nuget:
    - name: Push LLamaSharp packages to nuget.org
      run: dotnet nuget push ./temp/LLamaSharp*.nupkg --source https://www.nuget.org -k ${{ secrets.LLAMA_SHARP_NUGET_KEY }} --skip-duplicate
